language: python
python:
  - "3.8"
  - "3.8-dev"
  - "3.9-dev"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - python -m unittest discover -s tests -t tests

notifications:
  email: false
